"""Adapter for Semgrep static analysis."""

import json
import os
import shutil
import subprocess
import tempfile
import time
from datetime import datetime, timezone

from guardbench.adapters.base import ToolAdapter
from guardbench.schemas import Result, TestCase

_TIMEOUT_SECONDS = 60  # semgrep rule-fetch + scan can be slow

# Semgrep severity strings that trigger a block.
# ERROR maps to HIGH/CRITICAL findings in most rulesets.
_BLOCK_SEVERITIES = frozenset({"ERROR"})

# Map attack_type prefixes to file extensions for rendering.
_JS_KEYWORDS = frozenset({
    "xss", "prototype_pollution", "javascript", "js",
    "node", "dom", "eval_js",
})


def _find_semgrep() -> str:
    """Return the absolute path to ``semgrep``."""
    path = shutil.which("semgrep")
    if path:
        return path
    raise FileNotFoundError(
        "semgrep is not installed. Install it with: pipx install semgrep"
    )


_JS_HANDLER_MARKERS = ("execAsync", "child_process", "require(", "=>",
                       "await ", "process.env", "console.log", "`")


def _pick_extension(test_case: TestCase) -> str:
    """Choose .py or .js. attack_type is a weak signal; the handler body
    is the strong one (JS markers like execAsync, child_process,
    template-literal backticks)."""
    attack = test_case.attack_type.lower().replace("-", "_")
    for kw in _JS_KEYWORDS:
        if kw in attack:
            return ".js"
    # sniff handler body
    try:
        td = json.loads(test_case.attack_vector)
        h = td.get("handler", "") or ""
        if any(m in h for m in _JS_HANDLER_MARKERS):
            return ".js"
    except Exception:
        pass
    return ".py"


def _render_source(test_case: TestCase, ext: str) -> str:
    """Wrap the attack_vector in syntactically-valid source so Semgrep can
    parse and taint it.

    attack_vector is an MCP tool definition (JSON object with ``handler``
    and ``inputSchema.properties``). We extract the handler body and wrap
    it in a stub function whose parameters are the declared input-schema
    property names. That gives Semgrep bound identifiers to taint, so
    rules like ``python.lang.security.audit.dangerous-subprocess-use``
    can fire.

    If attack_vector isn't JSON (older entries, hand-authored cases), we
    fall through to the raw payload with a syntactic-sugar prefix so the
    file still parses when the payload happens to be valid code.
    """
    raw = test_case.attack_vector
    try:
        td = json.loads(raw)
        handler = td.get("handler", "")
        props = (td.get("inputSchema") or {}).get("properties") or {}
        params = ", ".join(props.keys())
    except Exception:
        td, handler, params = None, None, None

    if ext == ".js":
        if handler is not None:
            header = (
                "// auto-generated by guardbench — handler extracted from "
                "MCP tool definition\n"
            )
            body = "\n".join("  " + ln for ln in handler.splitlines()) or "  ;"
            return f"{header}function probe({params}) {{\n{body}\n}}\n"
        return f"// auto-generated by guardbench\n{raw}\n"

    # Python path
    if handler is not None:
        header = (
            "# auto-generated by guardbench — handler extracted from MCP tool\n"
            "import base64, subprocess, os, shutil, tempfile, importlib, "
            "re, json, time  # bound so Semgrep resolves calls\n"
        )
        body = "\n".join("    " + ln for ln in handler.splitlines()) or "    pass"
        return f"{header}def probe({params}):\n{body}\n"

    return f"# auto-generated by guardbench\n{raw}\n"


class SemgrepMCPAdapter(ToolAdapter):
    def __init__(self) -> None:
        self._bin: str = ""

    @property
    def name(self) -> str:
        return "semgrep"

    def setup(self) -> None:
        self._bin = _find_semgrep()

    def evaluate(self, test_case: TestCase) -> Result:
        if not self._bin:
            self.setup()

        tmpdir = tempfile.mkdtemp(prefix="guardbench-")
        try:
            return self._run(test_case, tmpdir)
        finally:
            shutil.rmtree(tmpdir, ignore_errors=True)

    # ------------------------------------------------------------------

    def _run(self, test_case: TestCase, tmpdir: str) -> Result:
        ext = _pick_extension(test_case)
        src_path = os.path.join(tmpdir, f"probe_{test_case.id}{ext}")
        with open(src_path, "w") as f:
            f.write(_render_source(test_case, ext))

        cmd = [
            self._bin, "scan",
            "--config", "auto",
            "--json",
            "--quiet",
            src_path,
        ]

        t0 = time.monotonic()
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired:
            latency_ms = int((time.monotonic() - t0) * 1000)
            return Result(
                test_case_id=test_case.id,
                tool_name=self.name,
                blocked=False,
                confidence=0.0,
                explanation=f"subprocess timed out after {_TIMEOUT_SECONDS}s",
                latency_ms=latency_ms,
                raw_output={"error": "timeout"},
                timestamp=datetime.now(timezone.utc),
                error="timeout",
            )
        latency_ms = int((time.monotonic() - t0) * 1000)

        stdout = proc.stdout.strip()
        if not stdout:
            return Result(
                test_case_id=test_case.id,
                tool_name=self.name,
                blocked=False,
                confidence=0.0,
                explanation=f"semgrep produced no JSON output (exit code {proc.returncode})",
                latency_ms=latency_ms,
                raw_output={
                    "stderr": proc.stderr[-2000:] if proc.stderr else "",
                    "exit_code": proc.returncode,
                },
                timestamp=datetime.now(timezone.utc),
                error=f"no_output_exit_{proc.returncode}",
            )

        try:
            raw = json.loads(stdout)
        except json.JSONDecodeError as exc:
            return Result(
                test_case_id=test_case.id,
                tool_name=self.name,
                blocked=False,
                confidence=0.0,
                explanation=f"malformed JSON from semgrep: {exc}",
                latency_ms=latency_ms,
                raw_output={"stdout_head": stdout[:500]},
                timestamp=datetime.now(timezone.utc),
                error="malformed_json",
            )

        return self._parse(test_case, raw, latency_ms)

    # ------------------------------------------------------------------

    def _parse(self, test_case: TestCase, raw: dict, latency_ms: int) -> Result:
        findings: list[dict] = []

        for result in raw.get("results", []):
            rule_id = result.get("check_id", "")
            extra = result.get("extra", {})
            severity = extra.get("severity", "INFO")
            metadata = extra.get("metadata", {})

            findings.append({
                "rule_id": rule_id,
                "severity": severity,
                "impact": metadata.get("impact"),
                "confidence": metadata.get("confidence"),
                "message": extra.get("message", ""),
                "vulnerability_class": metadata.get("vulnerability_class", []),
            })

        blocking = [f for f in findings if f["severity"] in _BLOCK_SEVERITIES]
        blocked = len(blocking) > 0

        if blocked:
            rule_ids = sorted({f["rule_id"] for f in blocking})
            explanation = f"blocked by rules: {', '.join(rule_ids)}"
            confidence = 1.0
        elif findings:
            explanation = f"{len(findings)} finding(s) below block threshold"
            confidence = 0.5
        else:
            explanation = "no findings"
            confidence = 0.0

        return Result(
            test_case_id=test_case.id,
            tool_name=self.name,
            blocked=blocked,
            confidence=confidence,
            explanation=explanation,
            latency_ms=latency_ms,
            raw_output={"findings": findings, "semgrep_version": raw.get("version")},
            timestamp=datetime.now(timezone.utc),
        )
